name = "401k-tracker"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "dist"

# Environment Variables (configure in dashboard or via wrangler secrets)
# Use wrangler pages secret put PLAID_CLIENT_ID
# Use wrangler pages secret put PLAID_SECRET

# Note: Build configuration, cron triggers, and other settings
# are configured via Cloudflare dashboard or CLI commands
# nodejs_compat flag enables Node.js APIs (crypto, buffer, etc.) in Functions