name = "401k-tracker"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "dist"

# Note: Cron triggers for Pages need to be configured in Cloudflare dashboard
# Workers & Pages → Your project → Settings → Functions → Cron Triggers