name = "401k-tracker"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "dist"

# Daily holdings sync at 6 AM UTC (2 AM ET / 11 PM PT)
[triggers]
crons = ["0 6 * * *"]