name: Daily Transaction Sync

on:
  schedule:
    # Run daily at 6 AM UTC (2 AM ET / 11 PM PT)
    - cron: '0 6 * * *'
  workflow_dispatch: # Allows manual trigger from GitHub Actions tab

jobs:
  sync-transactions:
    runs-on: ubuntu-latest
    steps:
      - name: Sync Plaid Transactions
        run: |
          # Retry up to 3 times with exponential backoff
          max_attempts=3
          attempt=1

          while [ $attempt -le $max_attempts ]; do
            echo "Attempt $attempt of $max_attempts..."

            # Run curl and capture both output and exit code
            set +e  # Don't exit on error
            response=$(curl -X POST https://401k.mreedon.com/api/sync/transactions \
              -H "X-401K-Token: ${{ secrets.API_SHARED_TOKEN }}" \
              -H "Content-Type: application/json" \
              -w "\n%{http_code}" \
              --connect-timeout 10 \
              --max-time 60 \
              2>&1)  # Capture stderr too
            curl_exit=$?
            set -e  # Re-enable exit on error

            echo "Curl exit code: $curl_exit"

            if [ $curl_exit -eq 0 ]; then
              http_code=$(echo "$response" | tail -n1)
              body=$(echo "$response" | sed '$d')

              echo "HTTP Response code: $http_code"
              echo "Response body: $body"

              if [ "$http_code" -eq 200 ]; then
                echo "✅ Sync successful!"
                exit 0
              else
                echo "⚠️ HTTP error: $http_code"
              fi
            else
              echo "⚠️ Curl failed with exit code $curl_exit"
              echo "Error output: $response"
            fi

            if [ $attempt -lt $max_attempts ]; then
              wait_time=$((2 ** attempt))
              echo "⚠️ Waiting ${wait_time}s before retry..."
              sleep $wait_time
            fi

            attempt=$((attempt + 1))
          done

          echo "❌ All retry attempts failed"
          exit 1