name: Daily Transaction Sync

on:
  schedule:
    # Run daily at 6 AM UTC (2 AM ET / 11 PM PT)
    - cron: '0 6 * * *'
  workflow_dispatch: # Allows manual trigger from GitHub Actions tab

jobs:
  sync-transactions:
    runs-on: ubuntu-latest
    steps:
      - name: Sync Plaid Transactions
        run: |
          curl -X POST https://401k.mreedon.com/api/sync/holdings \
            -H "X-401K-Token: ${{ secrets.API_SHARED_TOKEN }}" \
            -H "Content-Type: application/json" \
            -v